authentication_path:
  required: true
  validation:
    - validate_is_existing_path
    - validate_str_is_valid_path
  tags:
    - authentication_file_lookup
  section: qTest Details
  section_order: 1


qTest_domain:
  required: true
  validation:
    - validate_https_url
  default: "https://"
  section: qTest Details
  section_order: 2


target_projects:
  required: true
  validation:
    - validate_int_list
    - validate_int_list_digits:
        digits: 6
  tags:
    - accept_multiple_values
  section: qTest Details
  section_order: 3


output_filetype:
  required: true
  validation:
    - validate_option:
        allowed_values:
          - sqlite
          - excel
          - csv
  section: Output Settings
  section_order: 1


log_name_prefix:
  required: false
  validation:
    - validate_log_prefix
  default: "qTest_export_"
  section: Output Settings
  section_order: 2


include_config_rules_in_output:
  required: false
  validation:
    - validate_option:
        allowed_values:
          - true
          - false
  default: "false"
  section: Output Settings
  section_order: 3

  max_concurrent_requests:
  required: true
  validation:
    - validate_int_range:
        min_value: 1
        max_value: 10
  default: 5
  section: Request Settings
  section_order: 1


retry_attempts:
  required: false
  validation:
    - validate_int_range:
        lower_limit: 0
        upper_limit: 10
  default: "0"
  section: Request Settings
  section_order: 2