qTest Domain: https://apitryout.qtestnet.com/
Authentication Path: auth\example.yaml

Target Projects:
  - 125598
  - 589654
  - 123456

Max Concurrent Requests: 1
output_filetype: sqlite

# include_config_rules_in_output: true